name: Fetch Livepeer Organization Contributors Info

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch_livepeer_contributors_info:
    name: Fetch Livepeer Contributors Info
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run script to fetch contributors info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: livepeer
        run: |
          python scripts/get_org_contributors_info.py

      - name: Publish contributors_info.json to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scripts/data
          publish_branch: gh-pages-data
